services:
  api:
    image: api-with-dapper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Server=db,1433;Database=ApiWithDapper;User Id=sa;Password=thisIsMssql@Password;TrustServerCertificate=True;
      - ConnectionStrings__Master=Server=db,1433;Database=master;User Id=sa;Password=thisIsMssql@Password;TrustServerCertificate=True;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      - internal
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "thisIsMssql@Password"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - internal

volumes:
  sql_data:

networks:
  internal:
    driver: bridge